/**
 * 
 */
package com.uberverse.arkcraft.deprecated;

/**
 * @author ERBF | Aug 9, 2016
 */
public enum EnumEngram
{

	STONE_PICK(1, 0),
	TORCH(1, 0),

	CAMPFIRE(2, 3),
	STONE_HATCHET(2, 3),
	SPEAR(2, 3),
	NOTE(2, 3),
	CLOTH_PANTS(2, 3),
	CLOTH_SHIRT(2, 3),
	THATCH_FOUNDATION(2, 3),
	THATCH_DOORFRAME(2, 3),

	WOODEN_CLUB(3, 4),
	WATERSKIN(3, 6),
	CLOTH_GLOVES(3, 3),
	CLOTH_BOOTS(3, 3),
	CLOTH_HAT(3, 3),
	WOODEN_SIGN(3, 3),
	HIDE_SLEEPING_BAG(3, 3),
	THATCH_ROOF(3, 3),
	THATCH_WALL(3, 3),
	THATCH_DOOR(3, 3),

	SLINGSHOT(5, 6),
	STORAGE_BOX(5, 6),
	SIMPLE_BED(5, 8),
	PHIOMIA_SADDLE(5, 6),
	MORTAR_AND_PESTLE(5, 6),
	SPARKPOWEDER(5, 3),
	BLOOD_EXTRACTION_SYRINGE(5, 6),
	NARCOTIC(5, 6),
	PAINTBRUSH(5, 3),
	SINGLE_PANEL_FLAG(5, 6),
	MULTI_PANEL_FLAG(5, 6),
	STANDING_TORCH(5, 6),
	SLOPED_THATCH_WALL_LEFT(5, 3),
	SLOPED_THATCH_WALL_RIGHT(5, 3),
	SLOPED_THATCH_ROOF(5, 3),
	WOODEN_FOUNDATION(5, 6),
	WOODEN_WALL(5, 7),

	COOKINGPOT(10, 9),
	CEMENTING_PASTE(10, 3),
	STIMULANT(10, 6),
	GUNPOWDER(10, 2),
	FLARE_GUN(10, 6),
	COMPASS(10, 5),
	SPYGLASS(10, 2),
	SMALL_CROP_PLOT(10, 9),
	BASIC_GRAVESTONE(10, 8),
	WARDRUMS(10, 6),
	PARASAUR_SADDLE(10, 9),
	ICHTHYOSAURUS_SADDLE(10, 8),
	STONE_IRRIGATION_PIPE_INTAKE(10, 5),
	STORNE_IRRIGATION_PIPE_STRAIGHT(10, 2),
	STONE_IRRIGATION_PIPE_TAP(10, 5),
	WOODEN_SPIKE_WALL(10, 4),
	WOODEN_WALL_SIGN(10, 2),
	WOODEN_CEILING(10, 6),
	SLOPED_WOOD_WALL_LEFT(10, 3),
	SLOPED_WOOD_WALL_RIGHT(10, 3),
	SLOPED_WOODEN_ROOF(10, 4),
	WOODEN_DOORFRAME(10, 6),;

	private String id;
	private int requiredLevel, unlockEP;

	EnumEngram(int requiredLevel, int unlockEP)
	{
		this.id = this.name();
		this.requiredLevel = requiredLevel;
		this.unlockEP = unlockEP;
	}

}
